# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b433a609539345cc01505cf0f96b5bac08e15216c88b53bc2199847aea41df124866851de03525358d8abaad8f4aeebf1123d88e04f2a64e713f63c7bfe9ee1c

test:
  secret_key_base: 5c4e985a3d04f8b10db595016175c277a31126756dc5cd4ff4632a321a2a6cf83af06aef0c65a44ef508db9f77533ace122150f4a78320b5538670f47dee59e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
